"""Unit tests for the mas v0.2 CLI surface.

All tests use fresh local installations (no network, no shared secrets).
Keys are generated by `mas init`; passphrases are never used.
"""

import json
import os
import sqlite3
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

PY = sys.executable
SRC = Path(__file__).resolve().parents[2] / "src"
RELEASE_SRC = Path(os.environ.get(
    "MAS_RELEASE_SRC", str(Path.home() / "workspace" / "mas-release" / "src")
))


def run_cli(state_dir, *args):
    """Run the CLI, return (exit_code, stdout, stderr)."""
    env = dict(os.environ)
    env["PYTHONPATH"] = f"{SRC}:{RELEASE_SRC}"
    proc = subprocess.run(
        [PY, "-m", "muse_agent_social.cli", "--state-dir", str(state_dir), *args],
        capture_output=True,
        text=True,
        env=env,
        timeout=120,
    )
    return proc.returncode, proc.stdout, proc.stderr


def db(state_dir):
    conn = sqlite3.connect(str(Path(state_dir) / "state.db"))
    conn.row_factory = sqlite3.Row
    return conn


class CliTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.a = self.root / "a"
        self.b = self.root / "b"
        self.relay = self.root / "relay"
        for d in (self.a, self.b, self.relay):
            d.mkdir(parents=True)

    def tearDown(self):
        self.tmp.cleanup()

    def init_pair(self):
        code, out, err = run_cli(self.a, "init", "--display-name", "Alice")
        self.assertEqual(code, 0, err)
        code, out, err = run_cli(self.b, "init", "--display-name", "Bob")
        self.assertEqual(code, 0, err)

    def pair_two(self):
        """Full pairing flow; returns the relationship id."""
        self.init_pair()
        invite = self.root / "invite.txt"
        code, out, err = run_cli(self.a, "pair", "invite", "--out", str(invite))
        self.assertEqual(code, 0, err)
        accept = self.root / "accept.json"
        # Accept is a two-run sticky flow: run 1 displays the verification
        # phrase and records it; run 2 confirms the human compared it.
        code, out, err = run_cli(
            self.b, "pair", "accept",
            "--invite-file", str(invite),
            "--out", str(accept),
        )
        self.assertEqual(code, 1, err)
        self.assertIn("phrase_confirmation_required", err)
        code, out, err = run_cli(
            self.b, "pair", "accept",
            "--invite-file", str(invite),
            "--i-compared-phrase",
            "--out", str(accept),
        )
        self.assertEqual(code, 0, err)
        commit = self.root / "commit.json"
        # Commit has the same two-run sticky phrase flow.
        code, out, err = run_cli(
            self.a, "pair", "commit",
            "--acceptance-file", str(accept),
            "--relay", "https://example.com/relay",
            "--transport", "local",
            "--local-relay-dir", str(self.relay),
            "--out", str(commit),
        )
        self.assertEqual(code, 1, err)
        self.assertIn("phrase_confirmation_required", err)
        code, out, err = run_cli(
            self.a, "pair", "commit",
            "--acceptance-file", str(accept),
            "--relay", "https://example.com/relay",
            "--transport", "local",
            "--local-relay-dir", str(self.relay),
            "--i-compared-phrase",
            "--out", str(commit),
        )
        self.assertEqual(code, 0, err)
        code, out, err = run_cli(
            self.b, "pair", "ingest",
            "--commit-file", str(commit),
            "--local-relay-dir", str(self.relay),
        )
        self.assertEqual(code, 0, err)
        rid = out.strip()
        assert rid, f"ingest printed no rid: stdout={out!r} stderr={err!r}"
        return rid

    def exchange_ready(self, rid):
        code, out, err = run_cli(
            self.a, "send", "--relationship", rid, "--type", "relationship.ready"
        )
        self.assertEqual(code, 0, err)
        code, out, err = run_cli(
            self.b, "send", "--relationship", rid, "--type", "relationship.ready"
        )
        self.assertEqual(code, 0, err)
        for _ in range(4):
            run_cli(self.a, "receive", "--json")
            run_cli(self.b, "receive", "--json")

    def test_version(self):
        code, out, err = run_cli(self.a, "--version")
        self.assertEqual(code, 0, err)
        self.assertIn("mas", out)

    def test_init_creates_installation(self):
        code, out, err = run_cli(self.a, "init", "--display-name", "Alice")
        self.assertEqual(code, 0, err)
        self.assertTrue((self.a / "agent-card.json").exists())
        self.assertTrue((self.a / "state.db").exists())
        self.assertTrue((self.a / "keys" / "master.seed").exists())
        # No secret material on stdout.
        self.assertNotIn("seed", out.lower())

    def test_pair_invite_requires_phrase_confirmation(self):
        self.init_pair()
        invite = self.root / "invite.txt"
        code, out, err = run_cli(self.a, "pair", "invite", "--out", str(invite))
        self.assertEqual(code, 0, err)
        code, out, err = run_cli(
            self.b, "pair", "accept", "--invite-file", str(invite)
        )
        self.assertNotEqual(code, 0)
        self.assertNotIn("Traceback", err)

    def test_expected_errors_have_no_traceback(self):
        self.init_pair()
        code, out, err = run_cli(
            self.a, "send",
            "--relationship", "00000000-0000-0000-0000-000000000000",
            "--type", "message.created", "--body", "x",
        )
        self.assertNotEqual(code, 0)
        self.assertNotIn("Traceback", err)
        self.assertNotIn("Traceback", out)
        self.assertIn("error", err)

    def test_end_to_end(self):
        rid = self.pair_two()
        self.exchange_ready(rid)

        # Both sides active.
        for d in (self.a, self.b):
            code, out, err = run_cli(d, "inspect", "relationships")
            self.assertEqual(code, 0, err)
            self.assertIn("state=active", out)

        # A sends a message.
        code, out, err = run_cli(
            self.a, "send", "--relationship", rid,
            "--type", "message.created", "--body", "Hello Bob",
        )
        self.assertEqual(code, 0, err)
        msg_id = out.strip().split()[1]

        # B receives, replies, reacts.
        code, out, err = run_cli(self.b, "receive", "--json")
        self.assertEqual(code, 0, err)
        report = json.loads(out)
        self.assertEqual(report["totals"]["quarantined"], 0)

        code, out, err = run_cli(
            self.b, "send", "--relationship", rid,
            "--type", "message.created", "--body", "Hi Alice",
            "--reply-to", msg_id,
        )
        self.assertEqual(code, 0, err)
        reply_id = out.strip().split()[1]

        code, out, err = run_cli(
            self.b, "send", "--relationship", rid,
            "--type", "reaction.added", "--target", msg_id, "--emoji", "👍",
        )
        self.assertEqual(code, 0, err)

        # Receive until quiescent on both sides.
        for _ in range(6):
            run_cli(self.a, "receive", "--json")
            run_cli(self.b, "receive", "--json")

        # No quarantines anywhere.
        for d in (self.a, self.b):
            conn = db(d)
            n = conn.execute(
                "SELECT COUNT(*) FROM receive_quarantine"
            ).fetchone()[0]
            conn.close()
            self.assertEqual(n, 0, f"quarantines in {d}")

        # Matching event sets (by type and sender order).
        def event_signature(d):
            conn = db(d)
            rows = conn.execute(
                "SELECT event_type, sender, sender_seq FROM events ORDER BY rowid"
            ).fetchall()
            conn.close()
            # Normalize sender to self/peer by comparing to own identity.
            card = json.loads((Path(d) / "agent-card.json").read_text())
            me = card["identity_id"]
            return [
                (r["event_type"], "self" if r["sender"] == me else "peer",
                 r["sender_seq"])
                for r in rows
            ]

        sig_a = event_signature(self.a)
        sig_b = event_signature(self.b)
        # Flip self/peer: A's self is B's peer. Insertion order differs
        # (the relay does not guarantee order), so compare as multisets.
        flipped_b = [(t, "peer" if w == "self" else "self", s) for t, w, s in sig_b]
        self.assertEqual(sorted(sig_a), sorted(flipped_b))

        # Matching projections: same messages and reactions.
        def projections(d):
            conn = db(d)
            msgs = [
                (r["event_id"], r["body"])
                for r in conn.execute("SELECT event_id, body FROM messages ORDER BY rowid")
            ]
            reacts = [
                (r["target_event_id"], r["emoji"], r["active"])
                for r in conn.execute("SELECT target_event_id, emoji, active FROM reactions")
            ]
            conn.close()
            return msgs, reacts

        msgs_a, reacts_a = projections(self.a)
        msgs_b, reacts_b = projections(self.b)
        self.assertEqual(msgs_a, msgs_b)
        self.assertEqual(reacts_a, reacts_b)
        bodies = [b for _, b in msgs_a]
        self.assertIn("Hello Bob", bodies)
        self.assertIn("Hi Alice", bodies)
        self.assertTrue(any(e == "👍" for _, e, _ in reacts_a))

        # Receipts were exchanged (each side saw the peer's accepted receipt).
        for d in (self.a, self.b):
            conn = db(d)
            n = conn.execute(
                "SELECT COUNT(*) FROM events WHERE event_type = 'receipt.accepted'"
            ).fetchone()[0]
            conn.close()
            self.assertGreaterEqual(n, 2)


if __name__ == "__main__":
    unittest.main()
